const players = [
  {
    id: 1,
    name: "Shai Gilgeous-Alexander",
    number: 2,
    age: 27,
    team: "Oklahoma City Thunder",
    teamShort: "OKC",
    conference: "West",
    position: "PG",
    ppg: 31.1,
    rpg: 4.3,
    apg: 6.6,
    spg: 1.4,
    blk: 0.8,
    fgPct: 55.3,
    threePct: 38.6,
    ftPct: 87.9,
    mvpRank: 2,
    funFact: "SGA led OKC to the best record in the NBA at just 27 years old.",

  },
  {
    id: 2,
    name: "Nikola Jokić",
    number: 15,
    age: 30,
    team: "Denver Nuggets",
    teamShort: "DEN",
    conference: "West",
    position: "C",
    ppg: 27.7,
    rpg: 12.9,
    apg: 10.7,
    spg: 1.4,
    blk: 0.8,
    fgPct: 56.9,
    threePct: 38.0,
    ftPct: 83.1,
    mvpRank: 1,
    funFact: "Jokić is a 3-time MVP and the only center to average a triple-double for a season.",

  },
  {
    id: 3,
    name: "Giannis Antetokounmpo",
    number: 34,
    age: 31,
    team: "Milwaukee Bucks",
    teamShort: "MIL",
    conference: "East",
    position: "PF",
    ppg: 27.6,
    rpg: 9.8,
    apg: 5.4,
    spg: 0.9,
    blk: 0.7,
    fgPct: 62.4,
    threePct: 33.3,
    ftPct: 65.0,
    mvpRank: null,
    funFact: "Giannis went from undrafted in Greece to 2-time MVP and NBA champion.",

  },
  {
    id: 4,
    name: "Luka Dončić",
    number: 77,
    age: 26,
    team: "Los Angeles Lakers",
    teamShort: "LAL",
    conference: "West",
    position: "PG",
    ppg: 33.5,
    rpg: 7.7,
    apg: 8.3,
    spg: 1.6,
    blk: 0.5,
    fgPct: 47.6,
    threePct: 36.6,
    ftPct: 78.0,
    mvpRank: 3,
    funFact: "Luka is the youngest player in NBA history to reach 10,000 career points.",

  },
  {
    id: 5,
    name: "Stephen Curry",
    number: 30,
    age: 37,
    team: "Golden State Warriors",
    teamShort: "GSW",
    conference: "West",
    position: "PG",
    ppg: 26.6,
    rpg: 3.6,
    apg: 4.7,
    spg: 1.1,
    blk: 0.4,
    fgPct: 46.8,
    threePct: 39.3,
    ftPct: 92.3,
    mvpRank: null,
    funFact: "Curry holds the all-time record for 3-pointers made and is the greatest shooter ever.",
  },
  {
    id: 6,
    name: "Anthony Edwards",
    number: 5,
    age: 24,
    team: "Minnesota Timberwolves",
    teamShort: "MIN",
    conference: "West",
    position: "SG",
    ppg: 28.8,
    rpg: 5.0,
    apg: 3.7,
    spg: 1.4,
    blk: 0.8,
    fgPct: 48.9,
    threePct: 39.9,
    ftPct: 79.6,
    mvpRank: null,
    funFact: "Ant-Man became the face of a Timberwolves franchise that hadn't won a playoff series in 20 years.",

  },
  {
    id: 7,
    name: "Jaylen Brown",
    number: 7,
    age: 29,
    team: "Boston Celtics",
    teamShort: "BOS",
    conference: "East",
    position: "SF",
    ppg: 28.7,
    rpg: 6.9,
    apg: 5.1,
    spg: 1.0,
    blk: 0.4,
    fgPct: 47.7,
    threePct: 34.7,
    ftPct: 79.5,
    mvpRank: null,
    funFact: "Brown was the 2024 NBA Finals MVP as the Celtics won their 18th championship.",

  },
  {
    id: 8,
    name: "Tyrese Maxey",
    number: 0,
    age: 25,
    team: "Philadelphia 76ers",
    teamShort: "PHI",
    conference: "East",
    position: "PG",
    ppg: 28.3,
    rpg: 4.1,
    apg: 6.6,
    spg: 1.9,
    blk: 0.8,
    fgPct: 46.2,
    threePct: 36.7,
    ftPct: 89.2,
    mvpRank: null,
    funFact: "Maxey improved his scoring average by over 10 points in just two seasons.",

  },
  {
    id: 9,
    name: "Kawhi Leonard",
    number: 2,
    age: 34,
    team: "LA Clippers",
    teamShort: "LAC",
    conference: "West",
    position: "SF",
    ppg: 27.9,
    rpg: 6.4,
    apg: 3.6,
    spg: 1.9,
    blk: 0.4,
    fgPct: 50.5,
    threePct: 38.7,
    ftPct: 89.2,
    mvpRank: null,
    funFact: "Kawhi is a 2-time Finals MVP — the only player to win it with two different small-market teams.",

  },
  {
    id: 10,
    name: "Donovan Mitchell",
    number: 45,
    age: 29,
    team: "Cleveland Cavaliers",
    teamShort: "CLE",
    conference: "East",
    position: "SG",
    ppg: 27.9,
    rpg: 4.5,
    apg: 5.7,
    spg: 1.5,
    blk: 0.3,
    fgPct: 48.3,
    threePct: 36.4,
    ftPct: 86.5,
    mvpRank: null,
    funFact: "Spida Mitchell led the Cavaliers to the best record in the East in 2023-24.",

  },
  {
    id: 11,
    name: "Kevin Durant",
    number: 35,
    age: 37,
    team: "Houston Rockets",
    teamShort: "HOU",
    conference: "West",
    position: "SF",
    ppg: 26.0,
    rpg: 5.5,
    apg: 4.8,
    spg: 0.8,
    blk: 0.9,
    fgPct: 52.0,
    threePct: 41.3,
    ftPct: 87.4,
    mvpRank: null,
    funFact: "KD is one of only four players in NBA history to score 30,000 career points.",

  },
  {
    id: 12,
    name: "Devin Booker",
    number: 1,
    age: 29,
    team: "Phoenix Suns",
    teamShort: "PHO",
    conference: "West",
    position: "SG",
    ppg: 26.1,
    rpg: 3.9,
    apg: 6.0,
    spg: 0.8,
    blk: 0.3,
    fgPct: 45.6,
    threePct: 33.0,
    ftPct: 87.3,
    mvpRank: null,
    funFact: "Booker scored 70 points in a single game in 2017 one of the highest totals in NBA history.",

  },
  {
    id: 13,
    name: "Jalen Brunson",
    number: 11,
    age: 29,
    team: "New York Knicks",
    teamShort: "NYK",
    conference: "East",
    position: "PG",
    ppg: 26.0,
    rpg: 3.3,
    apg: 6.8,
    spg: 0.8,
    blk: 0.1,
    fgPct: 46.7,
    threePct: 36.9,
    ftPct: 84.1,
    mvpRank: null,
    funFact: "Brunson carried the Knicks on his back through multiple playoff runs as their undisputed leader.",

  },
  {
    id: 14,
    name: "Jamal Murray",
    number: 27,
    age: 28,
    team: "Denver Nuggets",
    teamShort: "DEN",
    conference: "West",
    position: "PG",
    ppg: 25.4,
    rpg: 4.4,
    apg: 7.1,
    spg: 0.9,
    blk: 0.4,
    fgPct: 48.3,
    threePct: 43.5,
    ftPct: 88.7,
    mvpRank: null,
    funFact: "Murray averaged 26.1 PPG in the 2023 playoffs, leading Denver to their first ever championship.",

  },
  {
    id: 15,
    name: "Victor Wembanyama",
    number: 1,
    age: 22,
    team: "San Antonio Spurs",
    teamShort: "SAS",
    conference: "West",
    position: "C",
    ppg: 25.0,
    rpg: 11.5,
    apg: 3.1,
    spg: 1.0,
    blk: 3.1,
    fgPct: 51.2,
    threePct: 34.9,
    ftPct: 82.7,
    mvpRank: 4,
    funFact: "Wemby is the first rookie in NBA history to average 20+ points, 10+ rebounds, and 3+ blocks.",

  },
  {
    id: 16,
    name: "Deni Avdija",
    number: 8,
    age: 25,
    team: "Portland Trail Blazers",
    teamShort: "POR",
    conference: "West",
    position: "SF",
    ppg: 24.2,
    rpg: 6.9,
    apg: 6.7,
    spg: 0.8,
    blk: 0.6,
    fgPct: 46.2,
    threePct: 31.8,
    ftPct: 80.2,
    mvpRank: null,
    funFact: "Avdija was a surprise All-Star, becoming the first Trail Blazer selected since Damian Lillard.",

  },
  {
    id: 17,
    name: "Pascal Siakam",
    number: 43,
    age: 31,
    team: "Indiana Pacers",
    teamShort: "IND",
    conference: "East",
    position: "PF",
    ppg: 24.0,
    rpg: 6.6,
    apg: 3.8,
    spg: 1.1,
    blk: 0.4,
    fgPct: 48.4,
    threePct: 35.8,
    ftPct: 69.3,
    mvpRank: null,
    funFact: "Siakam went from the NBA G-League to All-Star starter in just four seasons.",

  },
  {
    id: 18,
    name: "Cade Cunningham",
    number: 2,
    age: 24,
    team: "Detroit Pistons",
    teamShort: "DET",
    conference: "East",
    position: "PG",
    ppg: 23.9,
    rpg: 5.5,
    apg: 9.9,
    spg: 1.4,
    blk: 0.8,
    fgPct: 46.1,
    threePct: 34.2,
    ftPct: 81.2,
    mvpRank: 5,
    funFact: "Cunningham led the Pistons to end the longest losing streak in NBA history.",

  },
  {
    id: 19,
    name: "Jalen Johnson",
    number: 1,
    age: 24,
    team: "Atlanta Hawks",
    teamShort: "ATL",
    conference: "East",
    position: "SF",
    ppg: 22.5,
    rpg: 10.3,
    apg: 7.9,
    spg: 1.2,
    blk: 0.4,
    fgPct: 48.9,
    threePct: 35.2,
    ftPct: 78.8,
    mvpRank: null,
    funFact: "Johnson broke out as one of the most versatile forwards in the league in 2024-25.",

  },
  {
    id: 20,
    name: "Norman Powell",
    number: 24,
    age: 32,
    team: "Miami Heat",
    teamShort: "MIA",
    conference: "East",
    position: "SG",
    ppg: 21.7,
    rpg: 3.5,
    apg: 2.5,
    spg: 1.1,
    blk: 0.2,
    fgPct: 47.0,
    threePct: 38.0,
    ftPct: 82.7,
    mvpRank: null,
    funFact: "Powell had a career year at 32, earning his first ever All-Star selection.",

  },
  {
    id: 21,
    name: "Brandon Ingram",
    number: 14,
    age: 28,
    team: "Toronto Raptors",
    teamShort: "TOR",
    conference: "East",
    position: "SF",
    ppg: 21.5,
    rpg: 5.6,
    apg: 3.7,
    spg: 0.8,
    blk: 0.7,
    fgPct: 47.7,
    threePct: 38.2,
    ftPct: 82.0,
    mvpRank: null,
    funFact: "Ingram was a former #2 overall pick who developed into a reliable All-Star scorer.",

  },
  {
    id: 22,
    name: "LeBron James",
    number: 23,
    age: 41,
    team: "Los Angeles Lakers",
    teamShort: "LAL",
    conference: "West",
    position: "SF",
    ppg: 20.9,
    rpg: 6.1,
    apg: 7.2,
    spg: 1.2,
    blk: 0.6,
    fgPct: 51.5,
    threePct: 31.7,
    ftPct: 73.7,
    mvpRank: null,
    funFact: "LeBron is the NBA's all-time scoring leader and was still an All-Star at 40 years old.",

  },
  {
    id: 23,
    name: "Alperen Şengün",
    number: 28,
    age: 23,
    team: "Houston Rockets",
    teamShort: "HOU",
    conference: "West",
    position: "C",
    ppg: 20.4,
    rpg: 8.9,
    apg: 6.2,
    spg: 1.2,
    blk: 1.1,
    fgPct: 51.9,
    threePct: 30.5,
    ftPct: 69.1,
    mvpRank: null,
    funFact: "Şengün is one of the most skilled passing big men in the NBA at just 23 years old.",

  },
  {
    id: 24,
    name: "Karl-Anthony Towns",
    number: 32,
    age: 30,
    team: "New York Knicks",
    teamShort: "NYK",
    conference: "East",
    position: "C",
    ppg: 20.1,
    rpg: 11.9,
    apg: 3.0,
    spg: 0.9,
    blk: 0.5,
    fgPct: 50.1,
    threePct: 36.8,
    ftPct: 85.8,
    mvpRank: null,
    funFact: "KAT is one of the most skilled shooting big men ever, hitting 3s at a guard-level rate.",

  },
  {
    id: 25,
    name: "Jalen Duren",
    number: 0,
    age: 22,
    team: "Detroit Pistons",
    teamShort: "DET",
    conference: "East",
    position: "C",
    ppg: 19.5,
    rpg: 10.5,
    apg: 2.0,
    spg: 0.8,
    blk: 0.8,
    fgPct: 65.0,
    threePct: 0.0,
    ftPct: 74.7,
    mvpRank: null,
    funFact: "Duren became one of the most efficient scorers in the league, shooting 65% from the field.",

  },
  {
    id: 26,
    name: "De'Aaron Fox",
    number: 5,
    age: 28,
    team: "San Antonio Spurs",
    teamShort: "SAS",
    conference: "West",
    position: "PG",
    ppg: 18.6,
    rpg: 3.8,
    apg: 6.2,
    spg: 1.2,
    blk: 0.3,
    fgPct: 48.6,
    threePct: 33.2,
    ftPct: 76.0,
    mvpRank: null,
    funFact: "Fox is one of the fastest players in the NBA and a nightmare in transition.",

  },
  {
    id: 27,
    name: "Scottie Barnes",
    number: 4,
    age: 24,
    team: "Toronto Raptors",
    teamShort: "TOR",
    conference: "East",
    position: "PF",
    ppg: 18.1,
    rpg: 7.5,
    apg: 5.9,
    spg: 1.4,
    blk: 1.5,
    fgPct: 50.7,
    threePct: 30.4,
    ftPct: 81.5,
    mvpRank: null,
    funFact: "Barnes won Rookie of the Year in 2022 and has become one of the most versatile defenders in the East.",

  },
  {
    id: 28,
    name: "Chet Holmgren",
    number: 7,
    age: 23,
    team: "Oklahoma City Thunder",
    teamShort: "OKC",
    conference: "West",
    position: "PF",
    ppg: 28.9,
    rpg: 7.8,
    apg: 6.3,
    spg: 1.3,
    blk: 3.5,
    fgPct: 55.7,
    threePct: 36.2,
    ftPct: 64.6,
    mvpRank: null,
    funFact: "Holmgren is one of the most unique players ever — a 7-footer who can shoot threes and block everything.",

  },
  {
    id: 29,
    name: "LeBron James",
    number: 6,
    age: 41,
    team: "Los Angeles Lakers",
    teamShort: "LAL",
    conference: "West",
    position: "SF",
    ppg: 20.9,
    rpg: 6.1,
    apg: 7.2,
    spg: 1.2,
    blk: 0.6,
    fgPct: 51.5,
    threePct: 31.7,
    ftPct: 73.7,
    mvpRank: null,
    funFact: "LeBron is the all-time NBA scoring leader and the greatest of his generation.",

  },
];
